### ISSUE TITLE
Saving the project does not update the progress indicator

### ISSUE THREAD

**Issue by firelad97** [Justin113D/TranslationEditor#1]
Similar issue: #2 
![Screenshot_20240918_032404](https://github.com/user-attachments/assets/4410e736-7235-48d3-a292-e40ff50cda39)
![Screenshot_20240918_032622](https://github.com/user-attachments/assets/5fd3ad3a-cc29-4712-9ba5-9430f8181e49)

The progress indicator is updated in real time as intended, but not after saving and loading the project file. As seen in the screenshot above, the progress indicator is not updated after opening the project file.

If I move on to the new node and put in a new text, it is updated accordingly:
![Screenshot_20240918_032956](https://github.com/user-attachments/assets/ac12ca3b-9215-48bf-a76b-03a01c6ede07)

The excepted result should update the progress indicator even after saving and loading the project file.

To reproduce this:
Make changes to the nodes and then save the project. Load the project with "Open Project" from File menu after restarting the editor.

**Comment by Justin113D** [comment]
Issue fixed in mentioning commit
