### ISSUE TITLE
Saving the project doesn't update 'Author' and 'Language' fields

### ISSUE THREAD

**Issue by firelad97** [Justin113D/TranslationEditor#2]
Similar issue: #1 
![Screenshot_20240918_033617](https://github.com/user-attachments/assets/d81e0b2c-a944-4e8c-a4ad-35a57856fd29)
![Screenshot_20240918_034009](https://github.com/user-attachments/assets/7b213330-11d8-4260-90ec-83f992dcfc3c)

Saving the project doesn't update both fields 'Author' and 'Language'.

To reproduce this:
Make changes to the nodes and then save the project. Load the project with "Open Project" from File menu after restarting the editor.

**Comment by Justin113D** [comment]
Issue fixed in mentioning commit
